language: node_js
node_js:
  - "8"
  - "6"
script: "npm test -- --runInBand"
sudo: false
cache:
  directories:
    - node_modules
global:
    - CC_TEST_REPORTER_ID=65cb1de293991a0fb25b4d9ec9d71a75c898b7007328d87a3fb3739932f14b6c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./core/server/cc-test-reporter
  - chmod +x ./core/server/cc-test-reporter
  - ./core/server/cc-test-reporter before-build
after_script:
  - cd core/server/
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 65cb1de293991a0fb25b4d9ec9d71a75c898b7007328d87a3fb3739932f14b6c
