language: node_js
node_js:
  - "8"
  - "6"
script: "npm test"
sudo: false
cache:
  directories:
    - node_modules
after_success:
  - |
      if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        if [[$TRAVIS_NODE_VERSION" = "6" ]]; then
          echo "Generate coverage..."
          npm install -g codeclimate-test-reporter
          codeclimate-test-reporter < core/server/test/coverage/lcov.info
        else
          echo "False DB and NODE_VERSION. No coverage generated."
        fi
      else
        echo "This is a PR. No coverage generated."
      fi
