version: '3'
services:
  db:
    image: timescale/timescaledb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coinolio
      POSTGRES_PASSWORD: test # UPDATE
      POSTGRES_DB: coinolio
    networks:
      - coinolio_net
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - coinolio_net
  api:
    build:
      context: .
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=db
      - DATABASE_USER=coinolio
      - DATABASE_PASSWORD=test # UPDATE
      - DATABASE_LOCATION=coinolio
      - REDIS_URL=redis://redis
      - SESSION_SECRET=thisisasecretshhh # UPDATE
      - TOKEN_SECRET=thisisanothersecret # UPDAT
      - DEBUG=*
    restart: on-failure
    networks:
      - coinolio_net
networks:
  coinolio_net:
    driver: bridge
