version: '3'
services:
  api:
    build:
      context: .
    command: npm start
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://db
      DATABASE_USER: coinolio
      DATABASE_PASSWORD: test # UPDATE
      DATABASE_LOCATION: coinolio
      REDIS_URL: redis://redis:6379
      SESSION_SECRET: thisisasecretshhh # UPDATE
      TOKEN_SECRET: thisisanothersecret # UPDATE
      DEBUG: '*'
    restart: on-failure
  db:
    image: timescale/timescaledb:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coinolio
      POSTGRES_PASSWORD: test # UPDATE
      POSTGRES_DB: coinolio
  redis:
    image: redis:alpine
    hostname: redis
    restart: always
    ports:
      - "6379:6379"

